---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-deployment-nodeselector
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: basicnodeapp
        image: buildmystartup/basicnodeapp:2
        ports:
        - name: nodejs-port
          containerPort: 3000
      nodeSelector:
        hardware: high-resources
